name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --dev

    - name: Run pytest
      run: uv run pytest

    - name: ruff check
      run:  uv tool run ruff check

    - name: ruff format
      run:  uv tool run ruff format --check

    - name: Run mypy
      run: uv run mypy .
